In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [3]:
pd.set_option('display.max_columns',None)
df.head(5)

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_7th Phase JP Nagar  location_Yelahanka  location_Kanakpura Road  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   0                        0   
3                            0                   0                        0   
4                            0                   0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Kasavanhalli  location_Bellandur  location_Begur Road  \
0                      0                   0                    0   
1               

In [4]:
df.describe()

bath      balcony        price  total_sqft_int          bhk  \
count  7120.000000  7120.000000  7120.000000     7120.000000  7120.000000   
mean      2.390871     1.572759    96.454991     1479.729806     2.465169   
std       0.876822     0.770583   116.185034      913.779769     0.841520   
min       1.000000     0.000000    10.000000      350.000000     1.000000   
25%       2.000000     1.000000    49.230000     1100.000000     2.000000   
50%       2.000000     2.000000    69.000000     1255.000000     2.000000   
75%       3.000000     2.000000   104.000000     1640.250000     3.000000   
max       9.000000     3.000000  2912.000000    30400.000000     9.000000   

       price_per_sqft  area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
count     7120.000000                    7120.000000              7120.000000   
mean      5923.806855                       0.750702                 0.182303   
std       2556.650935                       0.432637                 0.386121   
min       1250.000000                       0.000000                 0.000000   
25%       4416.761042                       1.000000                 0.000000   
50%       5417.855613                       1.000000                 0.000000   
75%       6618.285651                       1.000000                 0.000000   
max      35000.000000                       1.000000                 1.000000   

       area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
count          7120.000000                 7120.000000          7120.000000   
mean              0.061938                    0.792697             0.032865   
std               0.241060                    0.405403             0.178296   
min               0.000000                    0.000000             0.000000   
25%               0.000000                    1.000000             0.000000   
50%               0.000000                    1.000000             0.000000   
75%               0.000000                    1.000000             0.000000   
max               1.000000                    1.000000             1.000000   

       location_Sarjapur  Road  location_Electronic City  \
count              7120.000000               7120.000000   
mean                  0.025702                  0.022191   
std                   0.158257                  0.147315   
min                   0.000000                  0.000000   
25%                   0.000000                  0.000000   
50%                   0.000000                  0.000000   
75%                   0.000000                  0.000000   
max                   1.000000                  1.000000   

       location_Marathahalli  location_Raja Rajeshwari Nagar  \
count            7120.000000                     7120.000000   
mean                0.016292                        0.016292   
std                 0.126605                        0.126605   
min                 0.000000                        0.000000   
25%                 0.000000                        0.000000   
50%                 0.000000                        0.000000   
75%                 0.000000                        0.000000   
max                 1.000000                        1.000000   

       location_Haralur Road  location_Hennur Road  \
count            7120.000000           7120.000000   
mean                0.016292              0.015169   
std                 0.126605              0.122232   
min                 0.000000              0.000000   
25%                 0.000000              0.000000   
50%                 0.000000              0.000000   
75%                 0.000000              0.000000   
max                 1.000000              1.000000   

       location_Bannerghatta Road  location_Uttarahalli  location_Thanisandra  \
count                 7120.000000           7120.000000           7120.000000   
mean                     0.015169              0.014888              0.014466   
std                      0.122

In [5]:
df.keys()

Index(['bath', 'balcony', 'price', 'total_sqft_int', 'bhk', 'price_per_sqft',
       'area_typeSuper built-up  Area', 'area_typeBuilt-up  Area',
       'area_typePlot  Area', 'availability_Ready To Move',
       ...
       'location_Kalena Agrahara', 'location_Horamavu Agara',
       'location_Vidyaranyapura', 'location_BTM 2nd Stage',
       'location_Hebbal Kempapura', 'location_Hosur Road',
       'location_Horamavu Banaswadi', 'location_Domlur',
       'location_Mahadevpura', 'location_Tumkur Road'],
      dtype='object', length=108)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Columns: 108 entries, bath to location_Tumkur Road
dtypes: float64(5), int64(103)
memory usage: 5.9 MB


In [7]:
#split
x=df.drop('price',axis=1)
y=df['price']

In [8]:
#train split
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51)

In [10]:
print('x_train',x_train.shape)
print('y_train',y_train.shape)
print('x_test',x_test.shape)
print('y_test',y_test.shape)

x_train (5696, 107)
y_train (5696,)
x_test (1424, 107)
y_test (1424,)


In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
std=StandardScaler()

In [13]:
std.fit(x_train)


StandardScaler()

In [14]:
x_train_scaling=std.transform(x_train)

In [15]:
x_test_scaling=std.transform(x_test)

In [16]:
x_test_scaling

array([[ 0.71301986,  0.0112734 ,  0.30202307, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.58028511, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [ 1.86878568,  0.55008644,  0.62450413, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-1.59851179,  0.55008644, -1.03304852, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.38550655, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 ,  0.12917322, ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [17]:
x_train_scaling.mean().round(2)

0.0

In [18]:
x_train_scaling.std().round(2)

1.0

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [20]:
poly=PolynomialFeatures(degree=2)

In [21]:
poly.fit(x_train_scaling)

PolynomialFeatures()

In [22]:
x_train_poly=poly.transform(x_train_scaling)
x_test_poly=poly.transform(x_test_scaling)

In [23]:
x_train_poly.shape

(5696, 5886)

In [24]:
x_test_poly.shape

(1424, 5886)

In [25]:
y_train.shape

(5696,)

In [26]:
lr=LinearRegression()

In [27]:
lr.fit(x_train_poly,y_train)

LinearRegression()

In [28]:
lr.score(x_test_poly,y_test)

0.997740853359133

In [29]:
y_test_poly_predict=lr.predict(x_test_poly)
y_test_poly_predict

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [30]:
y_test_poly_predict=lr.predict(x_test_poly)
y_test_poly_predict

array([ 80.,  40., 120., ...,  32.,  63., 180.])

In [31]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [32]:
from sklearn.metrics import mean_squared_error

In [33]:
mse=mean_squared_error(y_test,y_test_poly_predict)
rmse=np.sqrt(mse)
mse,rmse

(45.39289093444931, 6.737424651485856)